### PR TITLE
Create inforgraphic for UBER

### PR DESCRIPTION
**Pull request by nam-t24**

### CODE REVIEW

**Comment by shreyavala** [comment]
Hi, could you edit this commit to just include infographics/UBER.png and notebooks/UBER.ipynb
only these 2 files are needed, so no  DS_Store

Thank you so much!

**Comment by nam-t24** [comment]
I believe ds_store has been deleted now. Let me know if there's anything else or if it's all good. Thanks!

**Comment by nam-t24** [comment]
> Hi, could you edit this commit to just include infographics/UBER.png and notebooks/UBER.ipynb
> only these 2 files are needed, so no DS_Store
> 
> Thank you so much!

I believe ds_store has been deleted now. Let me know if there's anything else or if it's all good. Thanks!

**Review by adityarathod — APPROVED** [review]
looks good

**Pull request merged**
