### PR TITLE
Added Moderna Infographic and Notebook

### PR DESCRIPTION
**Pull request by GaganBhat**

### CODE REVIEW

**Comment by adityarathod** [comment]
can you make your folder name lowercase? thanks

**Comment by GaganBhat** [comment]
Done @adityarathod

**Comment by adityarathod** [comment]
You didn't fix it, the diff still shows the uppercase folder names.

image

**Comment by GaganBhat** [comment]
I have never seen this happen before, when I clone my fork even though there are technically 4 folders but with different capitalization, MacOS seems to combine them and only show the two unique ones. 

image
image

Probably one of the weirdest things I've seen so far.

**Comment by adityarathod** [comment]
weird. do you want to reclone the repo and try again?

**Review by adityarathod — APPROVED** [review]

**Comment by GaganBhat** [comment]
Thanks, 

I find it super interesting that when I clone this repo by default macOS merges the two folders together into one and it appears as though only two folders exist in the file system even though there technically are 4. 

Referred to this when fixing it - https://stackoverflow.com/questions/6899582/i-change-the-capitalization-of-a-directory-and-git-doesnt-seem-to-pick-up-on-it

You learn something new everyday I guess.

**Pull request merged**
